### ISSUE TITLE
Firstime login 

### ISSUE THREAD

**Issue by rgnarok** [VAYUZ-VLCC/vlcc-api-issues#68]
It is showcasing to welcome back correct it

**Comment by rohitrvayuz** [comment]
This has been fixed.

**Comment by rgnarok** [comment]
Not fixed still it is showing the welcome screen please add the screen shot here

**Comment by rohitrvayuz** [comment]
![Screenshot_1641326871](https://user-images.githubusercontent.com/78350161/148117516-147bbaf9-9538-4519-87ae-4ed84b725352.png)
